# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Test Blog
tagline:          Test Blog Tagline
url:              http://mverardo.github.io/
paginate:         1
baseurl:          /
author:
  name:           Maurício Verardo
  url:            http://mverardo.github.io/
  email:          mauricio.verardo@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           
